# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [8]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://github.com/thieu1995/csv-files/blob/main/data/pandas/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [9]:
drinks = pd.read_csv('/content/drinks.csv')
display(drinks.head())

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

### Step 4. Which continent drinks more beer on average?

In [10]:
continent_beer_average = drinks.groupby('continent')['beer_servings'].mean()
display(continent_beer_average)

continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

### Step 5. For each continent print the statistics for wine consumption.

In [11]:
wine_stats_by_continent = drinks.groupby('continent')['wine_servings'].describe()
display(wine_stats_by_continent)

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [12]:
alcohol_consumption_mean = drinks.groupby('continent')[['beer_servings', 'spirit_servings', 'wine_servings']].mean()
display(alcohol_consumption_mean)

           beer_servings  spirit_servings  wine_servings
continent
AF             61.471698        16.339623      16.264151
AS             37.045455        60.840909       9.068182
EU            193.777778       132.555556     142.222222
OC             89.687500        58.437500      35.625000
SA            175.083333       114.750000      62.416667

### Step 7. Print the median alcohol consumption per continent for every column

In [13]:
alcohol_consumption_median = drinks.groupby('continent')[['beer_servings', 'spirit_servings', 'wine_servings']].median()
display(alcohol_consumption_median)

           beer_servings  spirit_servings  wine_servings
continent
AF                  32.0              3.0            2.0
AS                  17.5             16.0            1.0
EU                 219.0            122.0          128.0
OC                  52.5             37.0            8.5
SA                 162.5            108.5           12.0

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [14]:
pirit_consumption_stats = drinks.groupby('continent')['spirit_servings'].agg(['mean', 'min', 'max'])
display(spirit_consumption_stats)

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302