# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [15]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [16]:
url = 'https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')

### Step 4. See the first 10 entries

In [17]:
url = 'https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [18]:
# Solution 1
len(chipo)

4622

In [ ]:
# Solution 2

### Step 6. What is the number of columns in the dataset?

In [19]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [20]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [21]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [22]:
c = chipo.groupby('item_name')
c = c.sum(numeric_only=True)
c = c.sort_values(['quantity'], ascending=False)
c.head(1)

              order_id  quantity
item_name
Chicken Bowl    713926       761

### Step 10. For the most-ordered item, how many items were ordered?

In [23]:
c.head(1).quantity

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 11. What was the most ordered item in the choice_description column?

In [24]:
d = chipo.groupby('choice_description').sum(numeric_only=True)
d = d.sort_values(['quantity'], ascending=False)
d.head(1)

                    order_id  quantity
choice_description
[Diet Coke]           123455       159

### Step 12. How many items were orderd in total?

In [25]:
chipo.quantity.sum()

np.int64(4972)

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [26]:
chipo.item_price.dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [27]:
dollarizer = lambda x: float(x[1:-1])
chipo.item_price = chipo.item_price.apply(dollarizer)

#### Step 13.c. Check the item price type

In [28]:
chipo.item_price.dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [29]:
revenue = (chipo['quantity']*chipo['item_price']).sum()
print(f"Revenue was: ${round(revenue,2)}")

Revenue was: $39237.02

### Step 15. How many orders were made in the period?

In [30]:
total_orders = chipo.order_id.nunique()
print(f"Number of orders: {total_orders}")

Number of orders: 1834

### Step 16. What is the average revenue amount per order?

In [31]:
# Solution 1
print(f"Average revenue per order: ${round(revenue / total_orders, 2)}")

Average revenue per order: $21.39

In [ ]:
# Solution 2

### Step 17. How many different items are sold?

In [32]:
unique_items = chipo.item_name.nunique()
print(f"Number of different items sold: {unique_items}")

Number of different items sold: 50