# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [9]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [10]:
url = 'https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')
display(chipo.head())

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [11]:
chipo['item_price'] = chipo['item_price'].str.replace('$', '', regex=False).astype(float)

products_over_10 = chipo[chipo['item_price'] > 10.00]

num_unique_products_over_10 = products_over_10['item_name'].nunique()

print(f"Number of products that cost more than $10.00: {num_unique_products_over_10}")

Number of products that cost more than $10.00: 31

### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [12]:
item_prices = chipo[['item_name', 'item_price']].drop_duplicates()
display(item_prices)

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4237                    Chips and Guacamole        8.50
4354                       Steak Soft Tacos       18.50
4489                    Chips and Guacamole       17.80
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[209 rows x 2 columns]

### Step 6. Sort by the name of the item

In [13]:
sorted_item_prices = item_prices.sort_values(by='item_name')
display(sorted_item_prices)

              item_name  item_price
3389  6 Pack Soft Drink       12.98
298   6 Pack Soft Drink        6.49
4510      Barbacoa Bowl       11.49
3195      Barbacoa Bowl        8.69
95        Barbacoa Bowl        9.25
...                 ...         ...
186   Veggie Salad Bowl       11.25
3889  Veggie Soft Tacos       16.98
738   Veggie Soft Tacos       11.25
781   Veggie Soft Tacos        8.75
1395  Veggie Soft Tacos        8.49

[209 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered?

In [14]:
chipo['price_per_item'] = chipo['item_price'] / chipo['quantity']

most_expensive_item_idx = chipo['price_per_item'].idxmax()

most_expensive_item_row = chipo.loc[most_expensive_item_idx]

quantity_most_expensive = most_expensive_item_row['quantity']

print(f"The quantity of the most expensive item ordered is: {quantity_most_expensive}")
print(f"Details of the most expensive item:\n{most_expensive_item_row[['item_name', 'price_per_item', 'quantity']]}")

The quantity of the most expensive item ordered is: 2
Details of the most expensive item:
item_name         Steak Salad Bowl
price_per_item               11.89
quantity                         2
Name: 281, dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [15]:
veggie_salad_bowl_orders = chipo[chipo['item_name'] == 'Veggie Salad Bowl']
num_veggie_salad_bowl_orders = veggie_salad_bowl_orders.shape[0]

print(f"A 'Veggie Salad Bowl' was ordered {num_veggie_salad_bowl_orders} times.")

A 'Veggie Salad Bowl' was ordered 18 times.

### Step 9. How many times did someone order more than one Canned Soda?

In [16]:
canned_soda_orders = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]
num_canned_soda_multiple = canned_soda_orders.shape[0]

print(f"Someone ordered more than one 'Canned Soda' {num_canned_soda_multiple} times.")

Someone ordered more than one 'Canned Soda' 20 times.